### PR TITLE
Jpuerto/ubkg integration

### PR DESCRIPTION
**Pull request by jpuerto-psc**
This PR adds "ubkg_code" to the "value" dictionary. This will be used in ingest-api to connect up to UBKG and pull the canonical information from there. Once we've confirmed that functionality, we will remove the majority of the attributes under the "value" dictionary.

### CODE REVIEW

**Review by jswelling — COMMENTED** [review]
How did you figure out the mapping between rules and ubkg_code values?  Is there some automated tool or did you have to go through all of them by hand?  I presume these will continue to be updated as rules change.

**Review by jswelling — APPROVED** [review]

**Comment by AlanSimmons** [comment]
@jpuerto-psc Did you validate against what you get from the following endpoint?

https://ontology.api.hubmapconsortium.org/assayclasses?application_context=HUBMAP

**Comment by jpuerto-psc** [comment]
> @jpuerto-psc Did you validate against what you get from the following endpoint?
> 
> https://ontology.api.hubmapconsortium.org/assayclasses?application_context=HUBMAP

Yes, the only one missing from that endpoint is the rule we just chatted about `derived salmon_rnaseq_10x json-based`.

**Review by gesinaphillips — APPROVED** [review]

**Comment by AlanSimmons** [comment]
@jpuerto-psc Bill noticed that all of the current MUSIC datasets in provenance have `assaytype` of "MUSIC", not "music".

**Pull request merged**
